### PR TITLE
Fix logging setup in readme

### LINKED ISSUE #2: GitHubActions logger fails
I tried to use GitHubActions logger but it fails:

https://github.com/timholy/SnoopCompile.jl/runs/830320767
```julia
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::String) at ./client.jl:439
 [7] top-level scope at /home/runner/work/SnoopCompile.jl/SnoopCompile.jl/test/runtests.jl:2
 [8] include(::String) at ./client.jl:439
 [9] top-level scope at none:6
in expression starting at /home/runner/work/SnoopCompile.jl/SnoopCompile.jl/test/snoopi.jl:1
in expression starting at /home/runner/work/SnoopCompile.jl/SnoopCompile.jl/test/runtests.jl:1
ERROR: Package SnoopCompile errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Types.jl:53
 [2] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:1510
 [3] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:316
 [4] #test#68 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:297 [inlined]
 [5] #test#65 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:294 [inlined]
 [6] top-level scope at none:1
##[error]The process 'julia' failed with exit code 1
```

### PR DESCRIPTION
**Pull request by aminya**
Fixes #2

### CODE REVIEW

**Comment by christopher-dG** [comment]
Generally my expectation is for people to set the logger in runtests.jl, where there is no init function. Not sure how many people are going to use this as a non-test dependency.

**Comment by aminya** [comment]
@christopher-dG Now it coverts both usage.

**Comment by aminya** [comment]
@christopher-dG any news?

**Comment by christopher-dG** [comment]
Sorry for the delay, this slipped my mind. I'll go ahead and merge, although I may do some reformatting eventually. But the extra info is good, thanks!

**Pull request merged**
